[package]
name = "abc399"
version = "0.1.0"
edition = "2021"

[dependencies]
proconio = { version = "0.4", features = [
    "derive",
] }

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
]

[[bin]]
name = "a"
path = "a.rs"